### PR TITLE
[83] Update README for spOption

### PR DESCRIPTION
**Pull request by JustinKyleJames**

### CODE REVIEW

**Review by korydraughn — APPROVED** [review]
Looks good. Pound it.

**Review by alanking — APPROVED** [review]
Yep, # it.

**Comment by JustinKyleJames** [comment]
> Yep, # it.

Done

**Comment by korydraughn** [comment]
We don't have a 4-3-stable branch for this repo.

Do we need to create a new branch?

**Comment by trel** [comment]
i don't think so.

**Pull request merged**
