### PR TITLE
Michael changes

### PR DESCRIPTION
**Pull request by JustinKyleJames**

### CODE REVIEW

**Comment by trel** [comment]
we've got no issues for these... these are ready to be merged?

**Comment by JustinKyleJames** [comment]
> we've got no issues for these... these are ready to be merged?

I have added issues for these.  They are ready to be merged.

**Comment by trel** [comment]
okay, please # when ready - this is going into master.   we'll create a 4-2-stable once we release i suppose...

**Comment by JustinKyleJames** [comment]
> okay, please # when ready - this is going into master. we'll create a 4-2-stable once we release i suppose...

Done

**Pull request merged**
