### PR TITLE
[59] Update README for yum build instructions

### PR DESCRIPTION
**Pull request by JustinKyleJames**
Several Updates:

1.  Updated versions of clang and cmake.
2.  Added installation for make and epel-release.

### CODE REVIEW

**Comment by korydraughn** [comment]
I think we removed the dependency on jansson. It's possible some other 4.2 project still relies on it.

**Comment by JustinKyleJames** [comment]
I tested with clang6 and cmake3.11 and updated this pull request accordingly.

I added the jansson package install back in because it is in the CMakeLists.txt.  I don't believe this is required and have opened an issue on it but having it there won't hurt anything.

**Comment by JustinKyleJames** [comment]
Also note that the irods-dev* in the following lines needs to be altered for the specific version.  If you just do it as is it will upgrade to 4.3 which is not what a person would want who is building for 4.2.x.

```
sudo apt-get -y install irods-externals-cmake3.11.4-0 irods-externals-clang6.0-0 irods-externals-jansson2.7-0 irods-dev irods-runtime
```
```
sudo yum -y install irods-externals-cmake3.11.4-0 irods-externals-clang6.0-0 irods-externals-jansson2.7-0 irods-devel irods-runtime rpm-build
```

Should we update these to the following:

```
sudo apt-get -y install irods-externals-cmake3.11.4-0 irods-externals-clang6.0-0 irods-externals-jansson2.7-0 irods-dev=<version> irods-runtime
```
```
sudo yum -y install irods-externals-cmake3.11.4-0 irods-externals-clang6.0-0 irods-externals-jansson2.7-0 irods-devel-<version> irods-runtime rpm-build
```

**Comment by JustinKyleJames** [comment]
I updated the README to have the version selected for irods-dev(el) and irods-runtime.

Note that from debian I had to add a wildcard since the OS version is in the version string.

**Comment by trel** [comment]
i see it.

does the asterisk work as expected/designed?  from a repo?

**Comment by JustinKyleJames** [comment]
Yes, it does.
________________________________

**Comment by JustinKyleJames** [comment]
> got it - please squash to one.

done

**Review by alanking — APPROVED** [review]

**Comment by trel** [comment]
good good - please # it.

**Comment by trel** [comment]
@JustinKyleJames please # this commit

**Comment by JustinKyleJames** [comment]
I just pounded this.  Sorry about the delay.

**Comment by trel** [comment]
merging.

**Pull request merged**
