### PR TITLE
[77] Changed where keyword to lowercase (main)

### PR DESCRIPTION
**Pull request by JustinKyleJames**

### CODE REVIEW

**Review by korydraughn — APPROVED** [review]
Looks good.

Do we have a test for this?

**Comment by JustinKyleJames** [comment]
> Looks good.
> 
> Do we have a test for this?

We don't have automated testing for anything with this client.  I put an entry in my test plan to test it.

**Review by alanking — APPROVED** [review]
Ah, I see... no tests. Okay, please # if confirmed working.

**Comment by korydraughn** [comment]
> We don't have automated testing for anything with this client. I put an entry in my test plan to test it.

Consider creating an issue for adding automated tests.

**Comment by JustinKyleJames** [comment]
> > We don't have automated testing for anything with this client. I put an entry in my test plan to test it.
> 
> Consider creating an issue for adding automated tests.

Done

**Comment by JustinKyleJames** [comment]
> Ah, I see... no tests. Okay, please # if confirmed working.

Done

**Comment by trel** [comment]
I see https://github.com/irods/irods_client_globus_connector/issues/82

**Pull request merged**
