### PR TITLE
Issue 45 42stable

### PR DESCRIPTION
**Pull request by JustinKyleJames**
Leaving this a two commits for now.

The commit for issue 45 is the change for update time.  Most of the changes are simply moving code from a lambda function into a named method so that both the main method and file write threads can call this method.

The commit for issue 50 is moving the base64 encoding/decoding methods into this plugin.

### CODE REVIEW

**Comment by michaellink** [comment]
We've finished up testing on this and it looks good.  Thanks!

**Comment by JustinKyleJames** [comment]
Are we ready to pound?

**Review by korydraughn — APPROVED** [review]
Add the #'s

**Comment by JustinKyleJames** [comment]
Pound added.

**Comment by korydraughn** [comment]
Looks like you're missing the `irods/irods_client_globus_connector#` prefix on the issue number.

**Comment by korydraughn** [comment]
Ignore that. It doesn't look like you included that on previous PRs.

**Review by alanking — APPROVED** [review]

**Pull request merged**
